export const routeData = [
  // UZBEKISTAN
  {
    indexedName: 'uzbekistan',
    countryNameCyr: 'узбекистон',
    countryNameLat: "O'zbekiston",
    alias: [],
    regions: [
      {
        id: 1,
        name: 'Toshkent shahri',
        indexedName: 'tashkent_city',
        center: 'Toshkent',
        coords: { lat: 41.2995, lng: 69.2401 },
        alias: [
          'toshkent',
          'tashkent',
          'toshent',
          'toshken',
          'poytaxt',
          'tashkent city',
          'toshkent shahar',
          'tosh',
          'toshkent sh',
          'tashkent',
          'chilonzor',
          'mirobod',
          "mirzo ulug'bek",
          'olmazor',
          'sergeli',
          'shayxontohur',
          'uchtepa',
          'yakkasaroy',
          'yangihayot',
          'yashnobod',
          'yunusobod',
          'yangi toshkent',
          'taşkent',
          'towkent',
          'towken',
          'urikzor',
          'abu sahiy',
          'abusahiy',
          'nazarbek',
          'qoyliq',
          'kuyluk',
          'qoyluq',
          'kuylik',
          'kuychirchik',
          'chirchik',
          'chirchiq',
          'yuqorichirchik',
          'yukorichirchik',
          'xasanboy',
          'sergili',
          'yangiyol',
          'yangiyul',
        ],
      },
      {
        id: 2,
        name: 'Toshkent viloyati',
        indexedName: 'tashkent_region',
        center: 'Nurafshon',
        coords: { lat: 41.0057729, lng: 71.6436028 },
        alias: [
          'toshkent viloyati',
          'toshkent obl',
          'tashkent obl',
          'tashkent region',
          'nurafshon',
          'chirchiq',
          "yangiyo'l",
          'yangiyul',
          'bekobod',
          'olmaliq',
          'olmalik',
          'almalyk',
          'angren',
          'ahangaran',
          'ohangaron',
          'toytepa',
          'gazalkent',
          'chinoz',
          'zangota',
          'zangiota',
          'food city',
          'fud sity',
          'fud sitiy',
          'qibray',
          'kibray',
          'bektemir',
          'ohangaron',
          'boka',
        ],
      },
      {
        id: 3,
        name: 'Andijon viloyati',
        indexedName: 'andijan',
        center: 'Andijon',
        coords: { lat: 40.8153561, lng: 72.28375 },
        alias: [
          'andijon',
          'anjon',
          'anijon',
          'andijan',
          'andizhan',
          'andijanlik',
          'asaka',
          'shaxrixon',
          'and',
          'baliqchi',
          'jalaquduq',
          'qorasuv',
          'qorgontepa',
          'marhamat',
          'paxtobod',
          'shahrihon',
          "ulug'nor",
          'xonabod',
        ],
      },
      {
        id: 4,
        name: "Farg'ona viloyati",
        indexedName: 'ferghana',
        center: "Farg'ona",
        coords: { lat: 40.3855561, lng: 71.78375 },
        alias: [
          'fargona',
          'ferghana',
          "farg'ona",
          'fergana',
          'vodiy',
          'vadiy',
          "qo'qon",
          'margilon',
          'rishton',
          'oltiariq',
          'buvayda',
          'vadil',
          'vodil',
          'qoʻqon',
          'qoqon',
          'quqon',
          'kokand',
          'quva',
          'quvasoy',
          'kuvasoy',
          'toshloq',
          'uchkoprik',
          'xonabod',
          'yaypan',
          'qoshtepa',
          'oltinariq',
          'bogdod',
          'yazyavon',
          'kuva',
          'rishtan',
          'rishton',
          'kokon',
          'besharik',
        ],
      },
      {
        id: 5,
        name: 'Namangan viloyati',
        indexedName: 'namangan',
        center: 'Namangan',
        coords: { lat: 40.9555061, lng: 71.1097749 },
        alias: [
          'namangan',
          'namanganlik',
          'namangan viloyati',
          'chust',
          'kosonsoy',
          'pop',
          "uchqo'rg'on",
          'nam',
          'norin',
          'toraqorgon',
        ],
      },
      {
        id: 6,
        name: 'Sirdaryo viloyati',
        indexedName: 'syrdarya',
        center: 'Guliston',
        coords: { lat: 40.4837431, lng: 68.7878923 },
        alias: [
          'sirdaryo',
          'sirdaryo viloyati',
          'guliston',
          'yangiyer',
          'syrdarya',
          'sirdarya',
          'mirzaobod',
          'sardoba',
          'sayxunobod',
          'shirin',
          'yangiyer',
        ],
      },
      {
        id: 7,
        name: 'Jizzax viloyati',
        indexedName: 'jizzakh',
        center: 'Jizzax',
        coords: { lat: 40.1255561, lng: 67.84375 },
        alias: [
          'jizzax',
          'jizzakh',
          'djizak',
          'jizax',
          'zomin',
          'forish',
          'baxmal',
          'dashtobod',
          'gagarin',
          "g'allaorol",
          "mirzacho'l",
          'paxtakor',
          'sharof rashidov',
          'zafarobod',
        ],
      },
      {
        id: 8,
        name: 'Samarqand viloyati',
        indexedName: 'samarkand',
        center: 'Samarqand',
        alias: [
          'samarqand',
          'samarkand',
          'samarkandskaya oblast',
          'sam',
          "kattaqo'rg'on",
          'urgut',
          'samarkant',
          'semerkand',
          "bulg'ur",
          'ishtixon',
          'jomboy',
          'juma',
          'narpay',
          'nurobod',
          'oqdaryo',
          'pastdargom',
          'payariq',
          'qoshrabot',
          'toyloq',
          'bulungur',
          'mirbozor',
          'mirboz',
          'xaterchi',
          'pastarkent',
          'pastargon',
          'kattakurgan',
          'kattaqurgon',
          'kattaqorgon',
        ],
      },
      {
        id: 9,
        name: 'Buxoro viloyati',
        indexedName: 'bukhara',
        center: 'Buxoro',
        coords: { lat: 40.1255561, lng: 67.84375 },
        alias: [
          'buxoro',
          'bukhara',
          'buxara',
          'vuxoro',
          "g'ijduvon",
          'vobkent',
          "qorako'l",
          'jondor',
          'kogon',
          'olot',
          'qorakol',
          'qorovulbozor',
          'romitan',
          'gijduvon',
          'gijdvon',
          'gazli',
          'buhoro',
        ],
      },
      {
        id: 10,
        name: 'Navoiy viloyati',
        indexedName: 'navoi',
        center: 'Navoiy',
        alias: [
          'navoiy',
          'navoi',
          'navoiyskaya oblast',
          'uchquduq',
          'zarafshon',
          'karmana',
          'konimex',
          'nurota',
          'qiziltepa',
          'tomdi',
        ],
      },
      {
        id: 11,
        name: 'Qashqadaryo viloyati',
        indexedName: 'kashkadarya',
        center: 'Qarshi',
        alias: [
          'qashqadaryo',
          'kashkadarya',
          'kashkadaryo',
          'kashkadaryinskaya',
          'qarshi',
          'karshi',
          'nasaf',
          'shaxrisabz',
          'qash',
          'shahrisabz',
          'yakkabog',
          'yangi nishon',
          'yettitom',
          'chiroqchi',
          'guzor',
          'kasbi',
          'kitob',
          'koson',
          'muborak',
          'qamashi',
          'nishon',
        ],
      },
      {
        id: 12,
        name: 'Surxondaryo viloyati',
        indexedName: 'surkhandarya',
        center: 'Termiz',
        alias: [
          'surxondaryo',
          'surxandaryo',
          'surkhondarya',
          'surxandarya',
          'termiz',
          'termez',
          'denov',
          'surxon',
          'angor',
          'boysun',
          'jarqorgon',
          'muzrabot',
          'qumqorgon',
          'sherobod',
          'sherabad',
          "sho'rchi",
          'uchqizil',
          'surkhandarya',
          'surchondaryo',
          'denau',
        ],
      },
      {
        id: 13,
        name: 'Xorazm viloyati',
        indexedName: 'khorezm',
        center: 'Urganch',
        alias: [
          'xorazm',
          'khorezm',
          'kharezm',
          'urganch',
          'urgench',
          'xiva',
          'khiva',
          'shovot',
          'xonqa',
          'yangiariq',
          'xorazim',
          'horazm',
        ],
      },
      {
        id: 14,
        name: "Qoraqalpog'iston Respublikasi",
        indexedName: 'karakalpakstan',
        center: 'Nukus',
        alias: [
          "qoraqalpog'iston",
          'qoraqalpogiston',
          'karakalpakstan',
          'karakalpakiya',
          'nukus',
          'nokus',
          'qrq',
          "bo'ston",
          'chimboy',
          "mang'it",
          "mo'ynoq",
          'qongirot',
          'qoraqalpoq',
          'qaraqalpoq',
          'qaraqalpaq',
          'karakalpak',
          'akchulok',
        ],
      },
    ],
  },

  // RUSSIA
  {
    indexedName: 'russia',
    countryNameCyr: 'Россия',
    countryNameLat: 'Rossiya',
    alias: ['russia', 'rossiya', 'ru', 'rus'],
    regions: [
      {
        id: 1,
        name: 'Moskva',
        indexedName: 'moscow',
        center: 'Moskva',
        alias: [
          'moskva',
          'moscow',
          'moskovskaya oblast',
          'mo',
          'msk',
          'maskva',
        ],
      },
      {
        id: 2,
        name: 'Sankt-Peterburg',
        indexedName: 'saint_petersburg',
        center: 'Sankt-Peterburg',
        alias: [
          'saint petersburg',
          'st petersburg',
          'piter',
          'spb',
          'sankt-peterburg',
        ],
      },
      {
        id: 3,
        name: 'Novosibirsk',
        indexedName: 'novosibirsk',
        center: 'Novosibirsk',
        alias: ['novosibirsk', 'nvs', 'sibir', 'nsk'],
      },
      {
        id: 4,
        name: 'Yekaterinburg',
        indexedName: 'yekaterinburg',
        center: 'Yekaterinburg',
        alias: ['yekaterinburg', 'ekb', 'ekaterinburg', 'sverdlovsk', 'burg'],
      },
      {
        id: 5,
        name: 'Kazan',
        indexedName: 'kazan',
        center: 'Kazan',
        alias: ['kazan', 'qazan', 'tatarstan', 'qozon'],
      },
      {
        id: 6,
        name: 'Chelyabinsk',
        indexedName: 'chelyabinsk',
        center: 'Chelyabinsk',
        alias: ['chelyabinsk', 'chelyaba', 'chelabinsk', 'chel'],
      },
      {
        id: 7,
        name: 'Samara',
        indexedName: 'samara',
        center: 'Samara',
        alias: ['samara', 'kuybishev'],
      },
      {
        id: 8,
        name: 'Rostov-na-Donu',
        indexedName: 'rostov_on_don',
        center: 'Rostov-na-Donu',
        alias: ['rostov', 'rostov-on-don', 'rostov na donu', 'rnd'],
      },
      {
        id: 9,
        name: 'Ufa',
        indexedName: 'ufa',
        center: 'Ufa',
        alias: ['ufa', 'bashkortostan', 'bashkiria', 'sterlitamak'],
      },
      {
        id: 10,
        name: 'Volgograd',
        indexedName: 'volgograd',
        center: 'Volgograd',
        alias: ['volgograd', 'stalingrad'],
      },
      {
        id: 11,
        name: 'Krasnodar',
        indexedName: 'krasnodar',
        center: 'Krasnodar',
        alias: ['krasnodar', 'kuban', 'krd'],
      },
      {
        id: 12,
        name: 'Omsk',
        indexedName: 'omsk',
        center: 'Omsk',
        alias: ['omsk'],
      },
      {
        id: 13,
        name: 'Voronej',
        indexedName: 'voronezh',
        center: 'Voronezh',
        alias: ['voronezh', 'voronej'],
      },
      {
        id: 14,
        name: 'Kirov',
        indexedName: 'kirov',
        center: 'Kirov',
        alias: ['kirov', 'vyatka', 'kirovskaya oblast'],
      },
      {
        id: 15,
        name: 'Nizhny Novgorod',
        indexedName: 'nizhny_novgorod',
        center: 'Nizhny Novgorod',
        alias: [
          'nizhny novgorod',
          'nnov',
          'nn',
          'gorky',
          'nizhegorodskaya',
          'arzamas',
          'baraba',
        ],
      },
      {
        id: 16,
        name: 'Tomsk',
        indexedName: 'tomsk',
        center: 'Tomsk',
        alias: ['tomsk', 'tomskaya oblast', 'tomsk oblast', 'asino'],
      },
      {
        id: 17,
        name: 'Kemerovo',
        indexedName: 'kemerovo',
        center: 'Kemerovo',
        alias: ['kemerovo', 'kem', 'kuzbass', 'shcheglovsk', 'novokuznetsk'],
      },
      {
        id: 18,
        name: 'Altai Krai',
        indexedName: 'altay_krai',
        center: 'Barnaul',
        alias: ['altay krai', 'altay', 'barnaul', 'rubtsovsk', 'biysk'],
      },
      {
        id: 19,
        name: 'Arkhangelsk Oblast',
        indexedName: 'arkhangelsk_oblast',
        center: 'Arkhangelsk',
        alias: ['arkhangelsk', 'arkhangelskaya oblast', 'arkhangelsk oblast'],
      },
      {
        id: 20,
        name: 'Saratov',
        indexedName: 'saratov',
        center: 'Saratov',
        alias: ['saratov', 'saratovskaya oblast', 'saratov oblast'],
      },
      {
        id: 21,
        name: 'Ulyanovsk',
        indexedName: 'ulyanovsk',
        center: 'Ulyanovsk',
        alias: ['ulyanovsk', 'ulyanovskaya oblast', 'ulyanovsk oblast'],
      },
      {
        id: 22,
        name: 'Amur Oblast',
        indexedName: 'amur_oblast',
        center: 'Blagoveshchensk',
        alias: ['amur oblast', 'amurskaya oblast', 'blagoveshchensk', 'blg'],
      },
      {
        id: 23,
        name: 'Astrakhan Oblast',
        indexedName: 'astrakhan_oblast',
        center: 'Astrakhan',
        alias: [
          'astrakhan oblast',
          'astrakhanskaya oblast',
          'astrakhan',
          'ast',
        ],
      },
      {
        id: 24,
        name: 'Belgorod Oblast',
        indexedName: 'belgorod_oblast',
        center: 'Belgorod',
        alias: ['belgorod oblast', 'belgorodskaya oblast', 'belgorod', 'bel'],
      },
      {
        id: 25,
        name: 'Bryansk Oblast',
        indexedName: 'bryansk_oblast',
        center: 'Bryansk',
        alias: ['bryansk oblast', 'bryanskaya oblast', 'bryansk', 'brn'],
      },
      {
        id: 26,
        name: 'Vladimir Oblast',
        indexedName: 'vladimir_oblast',
        center: 'Vladimir',
        alias: ['vladimir oblast', 'vladimirskaya oblast', 'vladimir', 'vlm'],
      },
      {
        id: 27,
        name: 'Vologda Oblast',
        indexedName: 'vologda_oblast',
        center: 'Vologda',
        alias: ['vologda oblast', 'vologodskaya oblast', 'vologda', 'vol'],
      },
      {
        id: 28,
        name: 'Ivanovo Oblast',
        indexedName: 'ivanovo_oblast',
        center: 'Ivanovo',
        alias: ['ivanovo oblast', 'ivanovskaya oblast', 'ivanovo', 'iva'],
      },
      {
        id: 29,
        name: 'Irkutsk Oblast',
        indexedName: 'irkutsk_oblast',
        center: 'Irkutsk',
        alias: ['irkutsk oblast', 'irkutskaya oblast', 'irkutsk', 'irk'],
      },
      {
        id: 30,
        name: 'Kaliningrad Oblast',
        indexedName: 'kaliningrad_oblast',
        center: 'Kaliningrad',
        alias: [
          'kaliningrad oblast',
          'kaliningradskaya oblast',
          'kaliningrad',
          'klg',
        ],
      },
      {
        id: 31,
        name: 'Kaluga Oblast',
        indexedName: 'kaluga_oblast',
        center: 'Kaluga',
        alias: ['kaluga oblast', 'kaluzhskaya oblast', 'kaluga', 'klzh'],
      },
      {
        id: 32,
        name: 'Kostroma Oblast',
        indexedName: 'kostroma_oblast',
        center: 'Kostroma',
        alias: ['kostroma oblast', 'kostromskaya oblast', 'kostroma', 'kos'],
      },
      {
        id: 33,
        name: 'Kurgan Oblast',
        indexedName: 'kurgan_oblast',
        center: 'Kurgan',
        alias: ['kurgan oblast', 'kurganskaya oblast', 'kurgan', 'kug'],
      },
      {
        id: 34,
        name: 'Kursk Oblast',
        indexedName: 'kursk_oblast',
        center: 'Kursk',
        alias: ['kursk oblast', 'kurskaya oblast', 'kursk', 'krs'],
      },
      {
        id: 35,
        name: 'Lipetsk Oblast',
        indexedName: 'lipetsk_oblast',
        center: 'Lipetsk',
        alias: ['lipetsk oblast', 'lipetskaya oblast', 'lipetsk', 'lpt'],
      },
      {
        id: 36,
        name: 'Magadan Oblast',
        indexedName: 'magadan_oblast',
        center: 'Magadan',
        alias: ['magadan oblast', 'magadanskaya oblast', 'magadan', 'mag'],
      },
      {
        id: 37,
        name: 'Murmansk Oblast',
        indexedName: 'murmansk_oblast',
        center: 'Murmansk',
        alias: ['murmansk oblast', 'murmanskaya oblast', 'murmansk', 'mur'],
      },
      {
        id: 38,
        name: 'Novgorod Oblast',
        indexedName: 'novgorod_oblast',
        center: 'Veliky Novgorod',
        alias: ['novgorod oblast', 'novgorodskaya oblast', 'novgorod', 'nvg'],
      },
      {
        id: 39,
        name: 'Orenburg Oblast',
        indexedName: 'orenburg_oblast',
        center: 'Orenburg',
        alias: ['orenburg oblast', 'orenburgskaya oblast', 'orenburg', 'orb'],
      },
      {
        id: 40,
        name: 'Oryol Oblast',
        indexedName: 'oryol_oblast',
        center: 'Oryol',
        alias: ['oryol oblast', 'orlovskaya oblast', 'oryol', 'orel', 'orl'],
      },
      {
        id: 41,
        name: 'Penza Oblast',
        indexedName: 'penza_oblast',
        center: 'Penza',
        alias: ['penza oblast', 'penzenskaya oblast', 'penza', 'pnz'],
      },
      {
        id: 42,
        name: 'Pskov Oblast',
        indexedName: 'pskov_oblast',
        center: 'Pskov',
        alias: ['pskov oblast', 'pskovskaya oblast', 'pskov', 'psk'],
      },
      {
        id: 43,
        name: 'Ryazan Oblast',
        indexedName: 'ryazan_oblast',
        center: 'Ryazan',
        alias: ['ryazan oblast', 'ryazanskaya oblast', 'ryazan', 'ryaz'],
      },
      {
        id: 44,
        name: 'Sakhalin Oblast',
        indexedName: 'sakhalin_oblast',
        center: 'Yuzhno-Sakhalinsk',
        alias: [
          'sakhalin oblast',
          'sakhalinskaya oblast',
          'yuzhno-sakhalinsk',
          'yuskh',
        ],
      },
      {
        id: 45,
        name: 'Smolensk Oblast',
        indexedName: 'smolensk_oblast',
        center: 'Smolensk',
        alias: ['smolensk oblast', 'smolenskaya oblast', 'smolensk', 'smo'],
      },
      {
        id: 46,
        name: 'Tambov Oblast',
        indexedName: 'tambov_oblast',
        center: 'Tambov',
        alias: ['tambov oblast', 'tambovskaya oblast', 'tambov', 'tmb'],
      },
      {
        id: 47,
        name: 'Tver Oblast',
        indexedName: 'tver_oblast',
        center: 'Tver',
        alias: ['tver oblast', 'tverskaya oblast', 'tver', 'tve'],
      },
      {
        id: 48,
        name: 'Tula Oblast',
        indexedName: 'tula_oblast',
        center: 'Tula',
        alias: ['tula oblast', 'tulskaya oblast', 'tula', 'tul'],
      },
      {
        id: 49,
        name: 'Tyumen Oblast',
        indexedName: 'tyumen_oblast',
        center: 'Tyumen',
        alias: [
          'tyumen oblast',
          'tyumenskaya oblast',
          'tyumen',
          'tyum',
          'tobolsk',
        ],
      },
      {
        id: 50,
        name: 'Yaroslavl Oblast',
        indexedName: 'yaroslavl_oblast',
        center: 'Yaroslavl',
        alias: [
          'yaroslavl oblast',
          'yaroslavskaya oblast',
          'yaroslavl',
          'yarl',
        ],
      },
      {
        id: 51,
        name: 'Jewish Autonomous Oblast',
        indexedName: 'jewish_autonomous_oblast',
        center: 'Birobidzhan',
        alias: ['jewish oblast', 'evreyskaya oblast', 'birobidzhan', 'bir'],
      },
      {
        id: 52,
        name: 'Stavropol Krai',
        indexedName: 'stavropol_krai',
        center: 'Stavropol',
        alias: [
          'stavropol',
          'stavropol krai',
          'stavropolskaya oblast',
          'stav',
          'stv',
        ],
      },
    ],
  },

  // KAZAKHSTAN
  {
    indexedName: 'kazakhstan',
    countryNameCyr: 'Қозоғистон',
    countryNameLat: "Qozog'iston",
    alias: ['kazakhstan', 'kazaxstan', 'kz', 'kaz'],
    regions: [
      {
        id: 1,
        name: 'Olmaota',
        indexedName: 'almaty',
        center: 'Almaty',
        alias: ['almaty', 'almati', 'alma-ata', 'almaata', 'almatinskiy'],
      },
      {
        id: 2,
        name: 'Ostona',
        indexedName: 'astana',
        center: 'Astana',
        alias: ['astana', 'nur-sultan', 'nursultan', 'akmola'],
      },
      {
        id: 3,
        name: 'Chimkent',
        indexedName: 'shymkent',
        center: 'Shymkent',
        alias: ['shymkent', 'chimkent', 'shimkent', 'turkestan region'],
      },
      {
        id: 4,
        name: 'Aktau',
        indexedName: 'aktau',
        center: 'Aktau',
        alias: ['aktau', 'mangistau', 'shevchenko'],
      },
      {
        id: 5,
        name: 'Atirau',
        indexedName: 'atyrau',
        center: 'Atyrau',
        alias: ['atyrau', 'atirau', 'guryev'],
      },
      {
        id: 6,
        name: "Aqto'be",
        indexedName: 'aktobe',
        center: 'Aktobe',
        alias: ['aktobe', 'aktobe', 'aktyubinsk'],
      },
      {
        id: 7,
        name: "Qarag'anda",
        indexedName: 'karaganda',
        center: 'Karaganda',
        alias: ['karaganda', 'qaraganda'],
      },
      {
        id: 8,
        name: 'Taraz',
        indexedName: 'taraz',
        center: 'Taraz',
        alias: ['taraz', 'jambul', 'zhambyl'],
      },
      {
        id: 9,
        name: "Qizilo'rda",
        indexedName: 'kyzylorda',
        center: 'Kyzylorda',
        alias: ['kyzylorda', 'qizilorda', 'kizilorda'],
      },
      {
        id: 10,
        name: 'Pavlodar',
        indexedName: 'pavlodar',
        center: 'Pavlodar',
        alias: ['pavlodar'],
      },
    ],
  },

  // KYRGYZSTAN
  {
    indexedName: 'kyrgyzstan',
    countryNameCyr: 'Қирғизистон',
    countryNameLat: "Qirg'iziston",
    alias: ['kyrgyzstan', 'kirgiziya', 'kg'],
    regions: [
      {
        id: 1,
        name: 'Bishkek shahri',
        indexedName: 'bishkek',
        center: 'Bishkek',
        alias: ['bishkek', 'frunze', 'kg_capital'],
      },
      {
        id: 2,
        name: "O'sh shahri",
        indexedName: 'osh_city',
        center: "O'sh",
        alias: ['osh shahar', 'osh city'],
      },
      {
        id: 3,
        name: 'Chuy viloyati',
        indexedName: 'chuy',
        center: 'Bishkek',
        alias: ['chuy', 'chuy viloyati', 'tokmok', 'kant'],
      },
      {
        id: 4,
        name: "O'sh viloyati",
        indexedName: 'osh_region',
        center: "O'sh",
        alias: ['osh', 'osh region', 'uzgen', 'qorasuv'],
      },
      {
        id: 5,
        name: 'Jalolobod viloyati',
        indexedName: 'jalal-abad',
        center: 'Jalolobod',
        alias: ['jalal-abad', 'jalolobod', 'dzhalal-abad', "toshko'mir"],
      },
      {
        id: 6,
        name: "Issiqko'l viloyati",
        indexedName: 'issyk-kul',
        center: "Qoraqo'l",
        alias: ['issyk-kul', 'isik-kul', 'karakol', 'cholpon-ata'],
      },
      {
        id: 7,
        name: 'Norin viloyati',
        indexedName: 'naryn',
        center: 'Norin',
        alias: ['naryn', 'norin', 'at-bashi'],
      },
      {
        id: 8,
        name: 'Botken viloyati',
        indexedName: 'batken',
        center: 'Botken',
        alias: ['batken', 'botken', 'qizil-qiya', 'sulukta'],
      },
      {
        id: 9,
        name: 'Talas viloyati',
        indexedName: 'talas',
        center: 'Talas',
        alias: ['talas', 'talas viloyati', 'manas'],
      },
    ],
  },

  // TAJIKISTAN
  {
    indexedName: 'tajikistan',
    countryNameCyr: 'Тожикистон',
    countryNameLat: 'Tojikiston',
    alias: ['tajikistan', 'tadjikistan', 'tj'],
    regions: [
      {
        id: 1,
        name: 'Dushanbe',
        indexedName: 'dushanbe',
        center: 'Dushanbe',
        alias: ['dushanbe', 'poytaxt', 'dsh'],
      },
      {
        id: 2,
        name: "Sug'd viloyati",
        indexedName: 'sughd',
        center: 'Xujand',
        alias: [
          'sughd',
          'sogd',
          'khujand',
          'xujand',
          'leninobod',
          'khudzhand',
          'konibodom',
          'isfora',
          'panjakent',
          'istaron',
          'istarovshan',
        ],
      },
      {
        id: 3,
        name: 'Xatlon viloyati',
        indexedName: 'khatlon',
        center: 'Boxtar',
        alias: [
          'khatlon',
          'boxtar',
          'bokhtar',
          'qurgontepa',
          'kurgan-tyube',
          'kulob',
          'kulyab',
          'norak',
          'nurek',
        ],
      },
      {
        id: 4,
        name: "Tog'li-Badaxshon",
        indexedName: 'badakhshan',
        center: "Xorug'",
        alias: [
          'badakhshan',
          'badaxon',
          'khorugh',
          'xorug',
          'pamir',
          'pomir',
          'gbao',
        ],
      },
    ],
  },

  // BELARUS
  {
    indexedName: 'belarus',
    countryNameCyr: 'Беларусь',
    countryNameLat: 'Belarusiya',
    alias: ['belarus', 'belorussiya', 'by'],
    regions: [
      {
        id: 1,
        name: 'Minsk shahri',
        indexedName: 'minsk_city',
        center: 'Minsk',
        alias: ['minsk city', 'poytaxt', 'msq'],
      },
      {
        id: 2,
        name: 'Minsk viloyati',
        indexedName: 'minsk_region',
        center: 'Minsk',
        alias: ['minsk', 'minskaya', 'borisov', 'soligorsk'],
      },
      {
        id: 3,
        name: 'Brest viloyati',
        indexedName: 'brest',
        center: 'Brest',
        alias: ['brest', 'brestskaya', 'pinsk', 'baranovichi'],
      },
      {
        id: 4,
        name: 'Vitebsk viloyati',
        indexedName: 'vitebsk',
        center: 'Vitebsk',
        alias: ['vitebsk', 'vitsyebsk', 'polotsk', 'orsha'],
      },
      {
        id: 5,
        name: 'Gomel viloyati',
        indexedName: 'gomel',
        center: 'Gomel',
        alias: ['gomel', 'homyel', 'mozyr', 'zhlobin'],
      },
      {
        id: 6,
        name: 'Grodno viloyati',
        indexedName: 'grodno',
        center: 'Grodno',
        alias: ['grodno', 'hrodna', 'lida', 'slonim'],
      },
      {
        id: 7,
        name: 'Mogilev viloyati',
        indexedName: 'mogilev',
        center: 'Mogilev',
        alias: ['mogilev', 'mahibyow', 'bobruisk'],
      },
    ],
  },

  // TURKEY
  {
    indexedName: 'turkey',
    countryNameCyr: 'Туркия',
    countryNameLat: 'Turkiya',
    alias: ['turkey', 'turkiye', 'turkiya', 'tr'],
    regions: [
      {
        id: 1,
        name: 'Ankara',
        indexedName: 'ankara',
        center: 'Ankara',
        alias: ['ankara', 'capital', 'angora'],
      },
      {
        id: 2,
        name: 'Istanbul',
        indexedName: 'istanbul',
        center: 'Istanbul',
        alias: ['istanbul', 'stambul', 'constantinople'],
      },
      {
        id: 3,
        name: 'Izmir',
        indexedName: 'izmir',
        center: 'Izmir',
        alias: ['izmir', 'smirna'],
      },
      {
        id: 4,
        name: 'Antalya',
        indexedName: 'antalya',
        center: 'Antalya',
        alias: ['antalya', 'antaliya', 'alanya'],
      },
      {
        id: 5,
        name: 'Bursa',
        indexedName: 'bursa',
        center: 'Bursa',
        alias: ['bursa', 'brusa'],
      },
      {
        id: 6,
        name: 'Adana',
        indexedName: 'adana',
        center: 'Adana',
        alias: ['adana'],
      },
      {
        id: 7,
        name: 'Gaziantep',
        indexedName: 'gaziantep',
        center: 'Gaziantep',
        alias: ['gaziantep', 'antep'],
      },
      {
        id: 8,
        name: 'Konya',
        indexedName: 'konya',
        center: 'Konya',
        alias: ['konya', 'iconium'],
      },
      {
        id: 9,
        name: 'Mersin',
        indexedName: 'mersin',
        center: 'Mersin',
        alias: ['mersin', 'mersin'],
      },
    ],
  },

  // AZERBAIJAN
  {
    indexedName: 'azerbaijan',
    countryNameCyr: 'Озарбайжон',
    countryNameLat: 'Ozarbayjon',
    alias: ['azerbaijan', 'azerbaycan', 'az'],
    regions: [
      {
        id: 1,
        name: 'Baku',
        indexedName: 'baku',
        center: 'Baku',
        alias: ['baku', 'baki', 'capital'],
      },
      {
        id: 2,
        name: 'Ganja',
        indexedName: 'ganja',
        center: 'Ganja',
        alias: ['ganja', 'gancay', 'kirovabad'],
      },
      {
        id: 3,
        name: 'Sumqayit',
        indexedName: 'sumqayit',
        center: 'Sumqayit',
        alias: ['sumqayit', 'sumgait'],
      },
      {
        id: 4,
        name: 'Lankaran',
        indexedName: 'lankaran',
        center: 'Lankaran',
        alias: ['lankaran', 'lenkoran'],
      },
      {
        id: 5,
        name: 'Gabala',
        indexedName: 'gabala',
        center: 'Gabala',
        alias: ['gabala', 'qabala'],
      },
      {
        id: 6,
        name: 'Nakhchivan',
        indexedName: 'nakhchivan',
        center: 'Nakhchivan',
        alias: ['nakhchivan', 'naxcivan'],
      },
      {
        id: 7,
        name: 'Shaki',
        indexedName: 'shaki',
        center: 'Shaki',
        alias: ['shaki', 'sheki'],
      },
      {
        id: 8,
        name: 'Shamakhi',
        indexedName: 'shamakhi',
        center: 'Shamakhi',
        alias: ['shamakhi', 'samaxi'],
      },
      {
        id: 9,
        name: 'Mingachevir',
        indexedName: 'mingachevir',
        center: 'Mingachevir',
        alias: ['mingachevir', 'mingecevir'],
      },
    ],
  },

  // POLAND
  {
    indexedName: 'poland',
    countryNameCyr: 'Польша',
    countryNameLat: 'Polsha',
    alias: ['poland', 'polska', 'pl'],
    regions: [
      {
        id: 1,
        name: 'Warsaw',
        indexedName: 'warsaw',
        center: 'Warsaw',
        alias: ['warsaw', 'warszawa', 'varshava', 'capital', 'varsava'],
      },
      {
        id: 2,
        name: 'Krakow',
        indexedName: 'krakow',
        center: 'Krakow',
        alias: ['krakow', 'cracow', 'krakow'],
      },
      {
        id: 3,
        name: 'Lodz',
        indexedName: 'lodz',
        center: 'Lodz',
        alias: ['lodz', 'wodzi'],
      },
      {
        id: 4,
        name: 'Wroclaw',
        indexedName: 'wroclaw',
        center: 'Wroclaw',
        alias: ['wroclaw', 'breslau'],
      },
      {
        id: 5,
        name: 'Poznan',
        indexedName: 'poznan',
        center: 'Poznan',
        alias: ['poznan', 'posen'],
      },
      {
        id: 6,
        name: 'Gdansk',
        indexedName: 'gdansk',
        center: 'Gdansk',
        alias: ['gdansk', 'danzig'],
      },
      {
        id: 7,
        name: 'Szczecin',
        indexedName: 'szczecin',
        center: 'Szczecin',
        alias: ['szczecin', 'stettin'],
      },
      {
        id: 8,
        name: 'Lublin',
        indexedName: 'lublin',
        center: 'Lublin',
        alias: ['lublin'],
      },
      {
        id: 9,
        name: 'Katowice',
        indexedName: 'katowice',
        center: 'Katowice',
        alias: ['katowice', 'katovise'],
      },
      {
        id: 10,
        name: 'Bialystok',
        indexedName: 'bialystok',
        center: 'Bialystok',
        alias: ['bialystok', 'belostok'],
      },
    ],
  },
];
